#include "BaHunApp.h"
#include "Moose.h"
#include "AppFactory.h"

template<>
InputParameters validParams<BaHunApp>()
{
  InputParameters params = validParams<MooseApp>();

  params.set<bool>("use_legacy_uo_initialization") = false;
  params.set<bool>("use_legacy_uo_aux_computation") = false;
  return params;
}

BaHunApp::BaHunApp(const std::string & name, InputParameters parameters) :
    MooseApp(name, parameters)
{
  srand(processor_id());

  Moose::registerObjects(_factory);
  BaHunApp::registerObjects(_factory);

  Moose::associateSyntax(_syntax, _action_factory);
  BaHunApp::associateSyntax(_syntax, _action_factory);
}

BaHunApp::~BaHunApp()
{
}

void
BaHunApp::registerApps()
{
  registerApp(BaHunApp);
}

void
BaHunApp::registerObjects(Factory & factory)
{
}

void
BaHunApp::associateSyntax(Syntax & syntax, ActionFactory & action_factory)
{
}
